### ISSUE TITLE
Please introduce proper releases based on GitHub functionality and tags

### ISSUE THREAD

**Issue by OFGrau** [hooxSoftware/UnitTestLib#1]
@hooxSoftware it is quite difficult to figure out which is the latest version of your UnitTest Library. It would be awesome if you could do the following two things:

- Please use tags whenever a new version of your software is released. This would allow users to jump to the proper version they require, if they need to be backwards compatible for any given reason.
- Please execute a proper [GitHub release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/about-releases) everytime you advance the version number of the project. This way people would be able to directly select a released version to download from the projects release page or the side bar menu.

**Comment by hooxSoftware** [comment]
that's right. I will create a V1.0.2 Tag with the next release (coming soon) its possible to keep it actual.
